#!/usr/bin/env -S pnpm tsx
/**
 * One-off: overwrite the *published* audio on R2 with the CBR-encoded copy,
 * in place, so every reader gets exact seeking -- not just a build with the
 * files staged locally.
 *
 * This works because the published filename is hashed on the section TEXT
 * (see textbook-loader/renderers/audio/renderer.ts), not on the audio bytes.
 * Swapping the bytes at the same key changes nothing else: no code change,
 * no re-render, no new URL. `section-audio.ts`'s `cbr` vs `cdn` distinction
 * becomes moot for these sections (both are now the same constant-bitrate
 * file) but is harmless to leave in place.
 *
 * The normal build pipeline (`pushPublicFiles` in r2-cache.ts) deliberately
 * SKIPS keys that already exist in R2, specifically to avoid re-uploading
 * 100+ MB on every rebuild. That means a plain `pnpm build` will never do
 * this swap -- it has to be deliberate, which is what this script is for.
 *
 * Usage:
 *   R2_ENDPOINT=... R2_ACCESS_KEY_ID=... R2_SECRET_ACCESS_KEY=... R2_BUCKET=... \
 *     pnpm tsx scripts/swap-cbr-audio.ts            # dry run: lists what would change
 *   ... pnpm tsx scripts/swap-cbr-audio.ts --yes     # actually uploads
 *   ... pnpm tsx scripts/swap-cbr-audio.ts --yes 4   # only chapter 4
 *
 * Only touches sections whose CBR file is staged locally under
 * public/audio/ch{N}/ (see scripts/copy-chapter-audio.sh) -- nothing is
 * downloaded or generated by this script.
 *
 * This overwrites a live, publicly-served file. The published objects are
 * also served with a long-lived immutable Cache-Control, so an edge cache
 * (Cloudflare or similar, wherever this R2 bucket is fronted) may keep
 * serving the old bytes at that URL until purged -- check the CDN config
 * for how to purge /audio/* after running this with --yes.
 */
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3"
import { existsSync, readFileSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import chapterTimings from "../src/data/chapter-timing"

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, "..")

const args = process.argv.slice(2)
const dryRun = !args.includes("--yes")
const chapterFilter = args.find((a) => /^\d+$/.test(a))

function requireEnv(name: string): string {
  const value = process.env[name]
  if (!value) {
    console.error(`ERROR: ${name} is not set.`)
    process.exit(1)
  }
  return value
}

const config = {
  endpoint: requireEnv("R2_ENDPOINT"),
  accessKeyId: requireEnv("R2_ACCESS_KEY_ID"),
  secretAccessKey: requireEnv("R2_SECRET_ACCESS_KEY"),
  bucket: requireEnv("R2_BUCKET"),
}
const client = new S3Client({
  region: "auto",
  endpoint: config.endpoint,
  credentials: { accessKeyId: config.accessKeyId, secretAccessKey: config.secretAccessKey },
})

type Job = { chapter: number; section: number; key: string; localPath: string }

const jobs: Job[] = []
for (const [chapterStr, sections] of Object.entries(chapterTimings)) {
  const chapter = Number(chapterStr)
  if (chapterFilter && String(chapter) !== chapterFilter) continue
  for (const [sectionStr, timing] of Object.entries(sections)) {
    const localPath = join(ROOT, "public", timing.audioUrl)
    if (!existsSync(localPath)) continue // not staged locally -- nothing to swap in
    const key = new URL(timing.publishedUrl).pathname.replace(/^\//, "") // "audio/atlas-ch4-s2-<hash>.mp3"
    jobs.push({ chapter, section: Number(sectionStr), key, localPath })
  }
}

jobs.sort((a, b) => a.chapter - b.chapter || a.section - b.section)

if (jobs.length === 0) {
  console.log("No staged CBR files found under public/audio/ch*/. Run scripts/copy-chapter-audio.sh first.")
  process.exit(0)
}

console.log(`${dryRun ? "[DRY RUN] " : ""}${jobs.length} section(s) to overwrite on R2:\n`)
for (const job of jobs) {
  console.log(`  ${job.chapter}.${job.section}  ${job.key}`)
}

if (dryRun) {
  console.log("\nRe-run with --yes to actually overwrite these on R2.")
  process.exit(0)
}

console.log("\nUploading...")
for (const job of jobs) {
  await client.send(
    new PutObjectCommand({
      Bucket: config.bucket,
      Key: job.key,
      Body: readFileSync(job.localPath),
      ContentType: "audio/mpeg",
    }),
  )
  console.log(`  done: ${job.key}`)
}
console.log(`\nSwapped ${jobs.length} section(s) to CBR. Purge the CDN cache for /audio/* if reads look stale.`)
